apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-app-web-codigo-pvc
  labels:
    app: mi-app-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: "efs-sc" # EKS