apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mi-app-web-mariadb-pvc
  labels:
    app: mi-app-web
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "efs-sc" # PARA EKS
