apiVersion: v1
kind: Service
metadata:
  name: mi-app-web-mariadb-service
  labels:
    app: mi-app-web
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mi-app-web
    tier: database
  type: ClusterIP
