apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-web-nginx-deployment
  labels:
    app: mi-app-web
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app-web
      tier: frontend
  template:
    metadata:
      labels:
        app: mi-app-web
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: app-code
          persistentVolumeClaim:
            claimName: mi-app-web-codigo-pvc
        - name: nginx-config
          configMap:
            name: mi-app-web-nginx-config
