apiVersion: v1
kind: Service
metadata:
  name: mi-app-web-nginx-service
  labels:
    app: mi-app-web
    tier: frontend
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: mi-app-web
    tier: frontend
  type: LoadBalancer
