name: Cluster EKS Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Escribe 'yes' para destruir"
        required: true
        default: "no"

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name nodo --region us-east-1

      - name: Confirm destruction
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }}
        run: |
          echo "Por favor, escribe 'yes' para confirmar."
          exit 1

      - name: Eliminar todo
        run: kubectl delete -f .

      # Drivers de EFS
      - name: Delete EFS CSI driver
        run: |
          kubectl delete -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.5"
          kubectl get pods -n kube-system

      - name: Todo limpio
        run: kubectl get all